services:
  db:
    image: postgres:15
    container_name: chokoi_db

    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ./apps/chokoi_app
      dockerfile: Dockerfile

    container_name: chokoi_streamlit

    restart: always

    ports:
      - "8501:8501"

    env_file:
      - .env

    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    depends_on:
      - db

    volumes:
      - ./apps/chokoi_app:/app

volumes:
  postgres_data: